### ISSUE TITLE
Add a combat tracker

### ISSUE THREAD

**Issue by astralfrontier** [astralfrontier/megalos#27]
Combat tracking should account for:

- [x] Grit
- [x] Player initiative (slow or fast actions)
- [x] Enemy initiative (including minion, elite, boss enemies)
- [x] Conditions on enemies
